spring:
  application:
    name: ai-data-collector
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

openapi:
  name: ai-data-collector
  title: AI Data Collector
  version: '@project.version@'
