openapi: 3.1.0
info:
  title: AI Data Collector
  contact: { }
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: "1.0"
servers:
  - url: http://localhost:58831
    description: Generated server url
paths:
  /{municipalityId}/confluence/webhook-event:
    post:
      tags:
        - Confluence Datasource Resources
      summary: Receives and handles incoming Confluence webhook data
      operationId: handleWebhookEvent
      parameters:
        - name: municipalityId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConfluenceWebhookData"
        required: true
      responses:
        "200":
          description: Ok
  /api-docs:
    get:
      tags:
        - API
      summary: OpenAPI
      operationId: getApiDocs
      responses:
        "200":
          description: OK
          content:
            application/yaml:
              schema:
                type: string
      x-auth-type: None
      x-throttling-tier: Unlimited
      x-wso2-mutual-ssl: Optional
components:
  schemas:
    ConfluenceWebhookData:
      type: object
      properties:
        timestamp:
          type: integer
          format: int64
        event:
          type: string
          description: Event type
          enum:
            - page_created
            - page_updated
            - page_removed
            - page_restored
        userKey:
          type: string
        page:
          $ref: "#/components/schemas/Page"
        updateTrigger:
          type: string
      required:
        - event
        - page
    Page:
      type: object
      properties:
        id:
          type: integer
          format: int64
      required:
        - id
  securitySchemes: { }
